# Generated by Django 3.0 on 2021-07-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.BigIntegerField(auto_created=True)),
                ('emp_name', models.CharField(max_length=2000)),
                ('emp_designation', models.CharField(max_length=2000)),
                ('address', models.CharField(max_length=2000)),
                ('city', models.CharField(max_length=2000)),
                ('mobile', models.CharField(max_length=100)),
            ],
        ),
    ]
