# Generated by Django 3.0 on 2021-07-29 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empmodels',
            name='emp_id',
        ),
    ]
